# Generated by Django 2.2 on 2019-04-19 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('uofm', models.CharField(max_length=64, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('bin_date', models.DateField(default=datetime.date.today, null=True, verbose_name='date created')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=64, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
