# Generated by Django 2.2 on 2019-04-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
