# Generated by Django 2.2 on 2019-04-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0002_product_creation_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bin_date',
            field=models.DateField(null=True),
        ),
    ]
