# Generated by Django 2.2 on 2019-04-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0003_auto_20190419_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bin_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uofm',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
