# Generated by Django 2.2 on 2019-04-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0004_auto_20190419_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bin_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='uofm',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
