# Generated by Django 2.2 on 2019-04-19 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0005_auto_20190419_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bin_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uofm',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
