# Generated by Django 2.2 on 2019-04-19 04:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0006_auto_20190419_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bin_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uofm',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='DailyDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgtree.Product')),
            ],
        ),
    ]
