# Generated by Django 2.2 on 2019-04-19 05:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0007_auto_20190419_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydeal',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailydeal',
            name='discount',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='dailydeal',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='dailydeal',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailydeal',
            name='promo_code',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dailydeal',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dailydeal',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date created'),
        ),
    ]
