# Generated by Django 2.2 on 2019-04-19 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0008_auto_20190419_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydeal',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dailydeal',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Start Date'),
        ),
    ]
