# Generated by Django 2.2 on 2019-04-19 05:19

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0009_auto_20190419_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='End Date')),
                ('promo_code', models.CharField(blank=True, default=None, max_length=32, null=True, unique=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('discount', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgtree.Product')),
            ],
        ),
        migrations.CreateModel(
            name='MedDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='End Date')),
                ('promo_code', models.CharField(blank=True, default=None, max_length=32, null=True, unique=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('discount', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgtree.Product')),
            ],
        ),
    ]
