# Generated by Django 2.2 on 2019-04-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0010_meddeal_recdeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='adult_use_item_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='adult_use_item_number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='buying_price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
