# Generated by Django 2.2 on 2019-04-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0011_auto_20190421_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adult_use_item_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='adult_use_item_number',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
