# Generated by Django 2.2 on 2019-04-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0013_auto_20190421_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adult_use_item_name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
