# Generated by Django 2.2 on 2019-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0008_auto_20190424_0906'),
        ('tgtree', '0014_auto_20190424_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='cloud_storage.CloudFile'),
        ),
    ]
