# Generated by Django 2.2 on 2019-04-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0016_auto_20190425_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='adult_use_item_number',
            new_name='adult_use_item_name',
        ),
    ]
