# Generated by Django 2.2 on 2019-04-25 19:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tgtree', '0018_auto_20190425_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudtenderQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_submitted', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_due', models.DateTimeField(blank=True, default=None, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('rating_one', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('rating_two', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgtree.Product')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
