# Generated by Django 2.2 on 2019-05-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0022_product_parent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='visible'),
        ),
    ]
