# Generated by Django 2.2 on 2019-05-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0023_product_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_sale',
            field=models.BooleanField(default=True, verbose_name='for_sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
    ]
