# Generated by Django 2.2 on 2019-05-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0024_auto_20190508_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discontinued',
            field=models.BooleanField(default=True, verbose_name='discontinued'),
        ),
    ]
