# Generated by Django 2.2 on 2019-05-08 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0025_product_discontinued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qty',
            new_name='inventory',
        ),
    ]
