# Generated by Django 2.2 on 2019-05-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0026_auto_20190508_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
