# Generated by Django 2.2 on 2019-05-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0029_remove_product_adult_use_item_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bar_code',
            new_name='upc',
        ),
    ]
