# Generated by Django 2.2 on 2019-05-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0031_auto_20190508_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='base_price',
        ),
    ]
