# Generated by Django 2.2 on 2019-05-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0033_product_msrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='job_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_changed_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
