# Generated by Django 2.2 on 2019-05-08 04:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tgtree', '0034_auto_20190508_0423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BudtenderQA',
            new_name='EmployeeProductQA',
        ),
    ]
