# Generated by Django 2.2 on 2019-05-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0036_auto_20190508_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpromotion',
            name='image_url',
        ),
    ]
