# Generated by Django 2.2 on 2019-05-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0038_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpromotion',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='tgtree.ProductTag'),
        ),
    ]
