# Generated by Django 2.2 on 2019-05-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0040_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('period', models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('yearly', 'yearly')], default='monthly', max_length=32)),
                ('short_description', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('long_description', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
    ]
