# Generated by Django 2.2 on 2019-05-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0041_membershipplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipplan',
            old_name='msrp',
            new_name='price',
        ),
    ]
