# Generated by Django 2.2 on 2019-05-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0042_auto_20190508_0515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
    ]
