# Generated by Django 2.2 on 2019-05-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree', '0045_usermembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
