# Generated by Django 2.2 on 2019-04-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='home', max_length=64, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
