# Generated by Django 2.2 on 2019-04-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0004_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='section_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_content.Section'),
        ),
    ]
