# Generated by Django 2.2 on 2019-04-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0007_auto_20190421_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='section_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_content.Section', unique=True),
        ),
    ]
