# Generated by Django 2.2 on 2019-04-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0008_auto_20190421_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='section_id',
            new_name='section',
        ),
    ]
