# Generated by Django 2.2 on 2019-04-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0017_auto_20190421_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='text_1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='text_2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='text_3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
