# Generated by Django 2.2 on 2019-04-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0018_auto_20190421_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=64, unique=True)),
                ('title_2', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('img_src', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_content.Section')),
            ],
        ),
    ]
