# Generated by Django 2.2 on 2019-04-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0019_headingleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='headingleft',
            name='align',
            field=models.CharField(choices=[('text-left', 'Left'), ('text-right', 'Right')], default='text-left', max_length=16),
        ),
    ]
