# Generated by Django 2.2 on 2019-04-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0020_headingleft_align'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeadingLeft',
            new_name='HeadlinerImg',
        ),
    ]
