# Generated by Django 2.2 on 2019-04-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0021_auto_20190421_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
