# Generated by Django 2.2 on 2019-04-23 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0022_delete_thing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('not_configured', 'not_configured'), ('triple_headliner_img', 'triple_headliner_img'), ('triple_headliner_text', 'triple_headliner_text'), ('jumbotron', 'jumbotron'), ('carousel', 'carousel'), ('headline_left', 'headline_left'), ('headline_right', 'headline_right'), ('footer', 'footer'), ('wysiwyg_row', 'wysiwyg_row')], default='not_configured', max_length=64),
        ),
        migrations.CreateModel(
            name='WysiwygRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
                ('col_1_html', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('col_2_html', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('col_3_html', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('col_4_html', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('row_type', models.CharField(choices=[('full', 'full'), ('halves', 'halves'), ('thirds', 'thirds'), ('quarters', 'quarters'), ('thirds_large_left', 'thirds_large_left'), ('thirds_large_right', 'thirds_large_right')], default='full', max_length=64)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_content.Section')),
            ],
        ),
    ]
