# Generated by Django 2.2 on 2019-04-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0023_auto_20190423_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wysiwygrow',
            name='col_1_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wysiwygrow',
            name='col_2_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wysiwygrow',
            name='col_3_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wysiwygrow',
            name='col_4_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
