# Generated by Django 2.2 on 2019-04-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0024_auto_20190423_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wysiwygrow',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_content.Section', unique=True),
        ),
    ]
