# Generated by Django 2.2 on 2019-04-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0025_auto_20190423_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='img_src_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TripleHeadlinerImage_img_src_1', to='cloud_storage.CloudFile'),
        ),
    ]
