# Generated by Django 2.2 on 2019-04-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0027_auto_20190424_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripleheadlinerimage',
            name='img_src_1',
        ),
    ]
