# Generated by Django 2.2 on 2019-04-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0030_auto_20190424_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripleheadlinerimage',
            name='img_src_3',
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='button_link_1',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='button_link_2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='button_link_3',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='button_title_1',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='button_title_2',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='button_title_3',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='title_1',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='title_2',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tripleheadlinerimage',
            name='title_3',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
