# Generated by Django 2.2 on 2019-04-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0011_auto_20190424_1453'),
        ('site_content', '0031_auto_20190424_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripleheadlinerimage',
            name='img_src_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TripleHeadlinerImage_img_src_3', to='cloud_storage.CloudFile'),
        ),
    ]
