# Generated by Django 2.2 on 2019-04-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0032_tripleheadlinerimage_img_src_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinerimg',
            name='img_src',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TripleHeadlinerImage_img_src', to='cloud_storage.CloudFile'),
        ),
    ]
