# Generated by Django 2.2 on 2019-04-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0034_auto_20190424_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinerimg',
            name='img_src',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HeadlinerImage_img_src', to='cloud_storage.CloudFile'),
        ),
    ]
