# Generated by Django 2.2 on 2019-04-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0037_auto_20190424_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WysiwygRow',
            new_name='RawHTMLRow',
        ),
    ]
