# Generated by Django 2.2 on 2019-04-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0011_auto_20190424_1453'),
        ('site_content', '0040_auto_20190424_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripleHeadlinerRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
                ('title_1', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('text_1', models.TextField(blank=True, null=True)),
                ('button_title_1', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('button_link_1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title_2', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('text_2', models.TextField(blank=True, default=None, null=True)),
                ('button_title_2', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('button_link_2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title_3', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('text_3', models.TextField(blank=True, default=None, null=True)),
                ('button_title_3', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('button_link_3', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('img_src_1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TripleHeadlinerRow_img_src_1', to='cloud_storage.CloudFile')),
                ('img_src_2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TripleHeadlinerRow_img_src_2', to='cloud_storage.CloudFile')),
                ('img_src_3', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TripleHeadlinerRow_img_src_3', to='cloud_storage.CloudFile')),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='site_content.Section')),
            ],
        ),
        migrations.DeleteModel(
            name='TripleHeadliner',
        ),
    ]
