# Generated by Django 2.2 on 2019-04-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0041_auto_20190424_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='PageSection',
        ),
    ]
