# Generated by Django 2.2 on 2019-04-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0042_auto_20190424_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='type',
            field=models.CharField(choices=[('not_configured', 'not_configured'), ('triple_headliner_img', 'triple_headliner_img'), ('triple_headliner_text', 'triple_headliner_text'), ('jumbotron', 'jumbotron'), ('carousel', 'carousel'), ('headline_left', 'headline_left'), ('headline_right', 'headline_right'), ('side_image_headliner', 'side_image_headliner'), ('footer', 'footer'), ('wysiwyg_row', 'wysiwyg_row')], default='not_configured', max_length=64),
        ),
    ]
