# Generated by Django 2.2 on 2019-04-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0043_auto_20190424_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='type',
            field=models.CharField(choices=[('not_configured', 'not_configured'), ('triple_headliner_img', 'triple_headliner_img'), ('triple_headliner_text', 'triple_headliner_text'), ('jumbotron', 'jumbotron'), ('carousel', 'carousel'), ('headline_left', 'headline_left'), ('headline_right', 'headline_right'), ('side_image_headliner', 'side_image_headliner'), ('footer', 'footer'), ('wysiwyg_row', 'wysiwyg_row'), ('custom_template', 'custom_template')], default='not_configured', max_length=64),
        ),
        migrations.CreateModel(
            name='CustomTemplateRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
                ('template_data', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_content.PageSection', unique=True)),
            ],
        ),
    ]
