# Generated by Django 2.2 on 2019-04-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0044_auto_20190425_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplaterow',
            name='sql_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
