# Generated by Django 2.2 on 2019-04-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0045_customtemplaterow_sql_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='section_eighteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_eighteen', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_eleven',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_eleven', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_fifteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_fifteen', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_fourteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_fourteen', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_nineteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_nineteen', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_seventeen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_seventeen', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_sixteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_sixteen', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_ten',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_ten', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_thirteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_thirteen', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twelve',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twelve', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twenty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twenty', to='site_content.PageSection'),
        ),
    ]
