# Generated by Django 2.2 on 2019-05-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0048_textbit'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='section_thirty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_thirty', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twentyeight',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twentyeight', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twentyfive',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twentyfive', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twentyfour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twentyfour', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twentynine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twentynine', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twentyone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twentyone', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twentyseven',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twentyseven', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twentysix',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twentysix', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twentythree',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twentythree', to='site_content.PageSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='section_twentytwo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_twentytwo', to='site_content.PageSection'),
        ),
    ]
