# Generated by Django 2.2 on 2019-05-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0053_customstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='leading_style',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_style', to='site_content.CustomStyle'),
        ),
        migrations.AddField(
            model_name='page',
            name='trailing_style',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailing_style', to='site_content.CustomStyle'),
        ),
    ]
