# Generated by Django 2.2 on 2019-05-01 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0055_page_aux_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='aux_section',
        ),
        migrations.AddField(
            model_name='page',
            name='aux_custom_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aux_custom_template', to='site_content.CustomTemplateRow'),
        ),
    ]
