# Generated by Django 2.2 on 2019-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0057_auto_20190501_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplaterow',
            name='json',
            field=models.BooleanField(default=False),
        ),
    ]
