# Generated by Django 2.2 on 2019-05-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0058_customtemplaterow_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtemplaterow',
            name='json',
        ),
        migrations.AddField(
            model_name='customtemplaterow',
            name='result_type',
            field=models.CharField(choices=[('table', 'table'), ('json_array', 'json_array'), ('json_obj', 'json_obj')], default='table', max_length=32),
        ),
    ]
