# Generated by Django 2.2 on 2019-05-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0060_auto_20190501_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawhtmlrow',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sideimageheadlinerrow',
            name='img_src',
        ),
        migrations.RemoveField(
            model_name='sideimageheadlinerrow',
            name='section',
        ),
        migrations.RemoveField(
            model_name='tripleheadlinerrow',
            name='img_src_1',
        ),
        migrations.RemoveField(
            model_name='tripleheadlinerrow',
            name='img_src_2',
        ),
        migrations.RemoveField(
            model_name='tripleheadlinerrow',
            name='img_src_3',
        ),
        migrations.RemoveField(
            model_name='tripleheadlinerrow',
            name='section',
        ),
        migrations.DeleteModel(
            name='CarouselRow',
        ),
        migrations.DeleteModel(
            name='RawHTMLRow',
        ),
        migrations.DeleteModel(
            name='SideImageHeadlinerRow',
        ),
        migrations.DeleteModel(
            name='TripleHeadlinerRow',
        ),
    ]
