# Generated by Django 2.2 on 2019-05-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0063_auto_20190503_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomTemplateRow',
            new_name='PageSection',
        ),
    ]
