# Generated by Django 2.2 on 2019-05-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0064_auto_20190503_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageSection',
            new_name='ContentSection',
        ),
    ]
