# Generated by Django 2.2 on 2019-05-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0065_auto_20190503_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='custom_section_eight',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_eighteen',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_eleven',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_fifteen',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_five',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_four',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_fourteen',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_nine',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_nineteen',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_one',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_seven',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_seventeen',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_six',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_sixteen',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_ten',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_thirteen',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_thirty',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_three',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twelve',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twenty',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twentyeight',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twentyfive',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twentyfour',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twentynine',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twentyone',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twentyseven',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twentysix',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twentythree',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_twentytwo',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_section_two',
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_eight',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_eight', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_eighteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_eighteen', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_eleven',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_eleven', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_fifteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_fifteen', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_five',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_five', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_four',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_four', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_fourteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_fourteen', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_nine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_nine', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_nineteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_nineteen', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_one',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_one', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_seven',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_seven', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_seventeen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_seventeen', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_six',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_six', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_sixteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_sixteen', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_ten',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_ten', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_thirteen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_thirteen', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_thirty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_thirty', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_three',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_three', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twelve',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twelve', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twenty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twenty', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twentyeight',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentyeight', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twentyfive',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentyfive', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twentyfour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentyfour', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twentynine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentynine', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twentyone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentyone', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twentyseven',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentyseven', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twentysix',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentysix', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twentythree',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentythree', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_twentytwo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentytwo', to='site_content.ContentSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_section_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_two', to='site_content.ContentSection'),
        ),
    ]
