# Generated by Django 2.2 on 2019-05-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0066_auto_20190503_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomScript',
            new_name='CustomCSS',
        ),
        migrations.RenameModel(
            old_name='CustomStyle',
            new_name='CustomJS',
        ),
    ]
