# Generated by Django 2.2 on 2019-05-04 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0067_auto_20190504_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='leading_script',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_script', to='site_content.CustomJS'),
        ),
        migrations.AlterField(
            model_name='page',
            name='leading_style',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_style', to='site_content.CustomCSS'),
        ),
        migrations.AlterField(
            model_name='page',
            name='trailing_script',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailing_script', to='site_content.CustomJS'),
        ),
        migrations.AlterField(
            model_name='page',
            name='trailing_style',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailing_style', to='site_content.CustomCSS'),
        ),
    ]
