# Generated by Django 2.2 on 2019-05-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0069_pagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_template', to='site_content.PageTemplate'),
        ),
    ]
