# Generated by Django 2.2 on 2019-05-08 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
                ('template_data', models.TextField(blank=True, null=True)),
                ('result_type', models.CharField(choices=[('table', 'table'), ('json_array', 'json_array'), ('json_object_agg', 'json_object_agg')], default='table', max_length=32)),
                ('sql_query', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=64, unique=True)),
                ('val', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomJS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=64, unique=True)),
                ('val', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=64, unique=True)),
                ('val', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextBitCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextBit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=64, unique=True)),
                ('val', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('text_bit_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_bit_category', to='cms.TextBitCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=64, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('aux_custom_template', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aux_custom_template', to='cms.ContentSection')),
                ('content_section_eight', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_eight', to='cms.ContentSection')),
                ('content_section_eighteen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_eighteen', to='cms.ContentSection')),
                ('content_section_eleven', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_eleven', to='cms.ContentSection')),
                ('content_section_fifteen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_fifteen', to='cms.ContentSection')),
                ('content_section_five', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_five', to='cms.ContentSection')),
                ('content_section_four', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_four', to='cms.ContentSection')),
                ('content_section_fourteen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_fourteen', to='cms.ContentSection')),
                ('content_section_nine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_nine', to='cms.ContentSection')),
                ('content_section_nineteen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_nineteen', to='cms.ContentSection')),
                ('content_section_one', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_one', to='cms.ContentSection')),
                ('content_section_seven', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_seven', to='cms.ContentSection')),
                ('content_section_seventeen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_seventeen', to='cms.ContentSection')),
                ('content_section_six', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_six', to='cms.ContentSection')),
                ('content_section_sixteen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_sixteen', to='cms.ContentSection')),
                ('content_section_ten', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_ten', to='cms.ContentSection')),
                ('content_section_thirteen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_thirteen', to='cms.ContentSection')),
                ('content_section_thirty', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_thirty', to='cms.ContentSection')),
                ('content_section_three', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_three', to='cms.ContentSection')),
                ('content_section_twelve', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twelve', to='cms.ContentSection')),
                ('content_section_twenty', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twenty', to='cms.ContentSection')),
                ('content_section_twentyeight', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentyeight', to='cms.ContentSection')),
                ('content_section_twentyfive', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentyfive', to='cms.ContentSection')),
                ('content_section_twentyfour', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentyfour', to='cms.ContentSection')),
                ('content_section_twentynine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentynine', to='cms.ContentSection')),
                ('content_section_twentyone', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentyone', to='cms.ContentSection')),
                ('content_section_twentyseven', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentyseven', to='cms.ContentSection')),
                ('content_section_twentysix', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentysix', to='cms.ContentSection')),
                ('content_section_twentythree', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentythree', to='cms.ContentSection')),
                ('content_section_twentytwo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_twentytwo', to='cms.ContentSection')),
                ('content_section_two', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_two', to='cms.ContentSection')),
                ('leading_script', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_script', to='cms.CustomJS')),
                ('leading_style', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_style', to='cms.CustomCSS')),
                ('page_template', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_template', to='cms.PageTemplate')),
                ('trailing_script', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailing_script', to='cms.CustomJS')),
                ('trailing_style', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailing_style', to='cms.CustomCSS')),
            ],
        ),
    ]
