# Generated by Django 2.2 on 2019-05-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_auth',
            field=models.CharField(choices=[('public', 'public'), ('employee', 'employee'), ('manager', 'manager'), ('member', 'member')], default='public', max_length=32),
        ),
    ]
