# Generated by Django 2.2 on 2019-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_page_page_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('title', 'page_auth')},
        ),
    ]
