# Generated by Django 2.2 on 2019-05-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190508_1118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_auth',
        ),
    ]
