# Generated by Django 2.2.1 on 2019-05-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190510_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='json_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
