# Generated by Django 2.2.1 on 2019-05-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, unique=True)),
                ('email', models.CharField(default=None, max_length=255, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
