# Generated by Django 2.2.1 on 2019-05-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree_info', '0002_newletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newletter',
            new_name='Newsletter',
        ),
    ]
