# Generated by Django 2.2.1 on 2019-05-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree_info', '0003_auto_20190514_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(default=None, max_length=255, unique=True)),
                ('info', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
