# Generated by Django 2.2.1 on 2019-05-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree_info', '0004_raffleticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMJNewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255, unique=True)),
                ('publication_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('img_url', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('text_preview', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
