# Generated by Django 2.2.1 on 2019-05-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree_info', '0005_mmjnewspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmjnewspost',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
