# Generated by Django 2.2.1 on 2019-05-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree_info', '0006_auto_20190514_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
