# Generated by Django 2.2.1 on 2019-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgtree_info', '0007_eventpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
